### ISSUE TITLE
Non-ASCII are not allowed in wallet path..

### ISSUE THREAD

**Issue by Baltsar** [monero-project/monero-core#820] opened 2017-08-14 12:10 UTC
![monero_ascii](https://user-images.githubusercontent.com/10773507/29270953-6b802932-80f9-11e7-84a2-68acf8ff1f2c.jpg)

I don't know if this is the place to post this but **I see this as an issue if Monero would spread internationally with different language.**

 I know you can just install on C: . Other people that are not so tech savvy, would probably not come to that conclusion. I can tell you what I did, a bit stressed during this process but I tried to change my user name in windows but catastrophic results.

Can it be solved and why is it not allowing other characters? Thanks.

**Comment by Jaqueeee** [comment] 2017-08-14 12:43
Duplicate of #199
Related to: https://github.com/monero-project/monero/issues/1390
Hopefully a windows dev can fix this soon™. 
+duplicate

**Closed** 2017-08-14 12:45 UTC
Labels: duplicate

**Comment by jw108** [comment] 2017-09-26 08:39
Hello all. The fix this issue can writing is right way to yours wallet parth, what does mean, you must write only latin words (name of folder) in the way to yours wallet path or wallet .key  
like this:
C:\Wallets\MONERO\monero-gui-0.11.0.0 
And after that  you not recieve some trouble with monero-gui wallet. You can recovering yours wallet from seed or launch wallet whitch made from monero cli. 
Good luck
