### ISSUE TITLE
Stronger Password Suggestions

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-core#281] opened 2016-12-14 18:36 UTC
The Monero GUI falls a little short when suggesting the strength of passwords. A 4 character password is considered "medium". Luckily, it takes 20 characters to get to "high".

The Monero wallet is a service that many people will keep substantial money in. The GUI should give stricter suggestions for passwords. I suggest the minimum for a "moderate" password should be 10 characters. I'd argue it should stay on the lowest setting if the password is less than 5 characters.

http://imgur.com/a/zCpam

**Comment by dEBRUYNE-1** [comment] 2016-12-14 19:03
Duplicate of #1.

**Comment by moneromooo-monero** [comment] 2016-12-16 00:41
https://github.com/monero-project/monero-core/pull/292

**Closed** 2017-03-25 15:28 UTC
