### ISSUE TITLE
History :: advanced filters not working

### ISSUE THREAD

**Issue by M5M400** [monero-project/monero-core#173] opened 2016-11-16 11:03 UTC
master 24a66c1, ubuntu 16.04.1 LTS amd64

I have a wallet with 33 transactions (31 incoming, 2 outgoing)

opening history, everything is OK. showing all transactions, sorted by block height desc.

![filter_all](https://cloud.githubusercontent.com/assets/22886679/20344652/e1693a0c-abf3-11e6-8766-e0b1451fbe40.png)

enabling advanced filters, selecting "sent" from the dropdown and click the "filter" button

expected behavior: shows only 2 outgoing transactions
actual behavior: shows all transactions

![sent](https://cloud.githubusercontent.com/assets/22886679/20344696/0b1b8d3c-abf4-11e6-9735-dc784b16532f.png)

adding limit from 0-1 XMR to the sent filter

expected behavior: shows all outgoing transactions <= 1XMR
actual behavior: shows ALL transactions <= 1XMR

![sent_1](https://cloud.githubusercontent.com/assets/22886679/20344738/33670b7c-abf4-11e6-9a0f-d147a9132c64.png)

uncheck "advanced filtering" and clicking "filter" button

expected behavior: reset to default date-based filter, showing all 33 transactions again
actual behavior: still showing transactions <=1 XMR

![disable_filter](https://cloud.githubusercontent.com/assets/22886679/20344819/899462b0-abf4-11e6-89a6-83fec0d71321.png)

Filter resets only on app restart.

**Comment by taushet** [comment] 2016-11-16 17:39
Confirmed

**Comment by moneromooo-monero** [comment] 2016-11-16 21:04
https://github.com/monero-project/monero-core/pull/176  (should fix all/most)

**Comment by M5M400** [comment] 2016-11-18 10:37
disabling advanced filters again: works
filtering sent/received: does not work

setting advanced filter to "sent" - still showing sent+received TXs

![screenshot from 2016-11-18 11-35-57](https://cloud.githubusercontent.com/assets/22886679/20427245/45d696b6-ad83-11e6-8e74-45873754511f.png)

**Comment by medusadigital** [comment] 2016-11-18 11:24
i could not reproduce this behaviour unfortunately on my side. im running together with https://github.com/monero-project/monero-core/pull/178

**Comment by medusadigital** [comment] 2017-08-07 20:13
seems good to me by now, closing until further notice.

+resolved

**Closed** 2017-08-07 20:15 UTC
Labels: resolved
